[tool.poetry]
name = "pyside-wrapper-yaboiteedoh"
version = "0.1.47"
description = ""
authors = ["yaboiteedoh <cook.brandon624@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.12, <3.14"
pyside6 = "^6.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
